package ui;

import javax.swing.*;

public class essaisConnexion extends JFrame {
    public static final int WIDTH = 500;
    public static final int HEIGHT = 500;

    private JPanel connexionPanel;
    private JPanel headPanel;
    private JPanel westPanel;
    private JPanel eastPanel;
    private JPanel southPanel;
    private JLabel imageCHUPP;
    private JLabel logoH2I;
    private JLabel mdpLabel;
    private JLabel identifiantLabel;
    private JLabel connexionLabel;
    private JTextField identifiantTextField;
    private JPasswordField passwordField;
    private JButton connexionButton;
    private JPanel resultPanel;

    public essaisConnexion() {
        setSize(WIDTH, HEIGHT);
        setContentPane(connexionPanel);
        setLocationRelativeTo(null);

    }
/*
//permet d'afficher le boutton pour dire que la connection a échoué, à mettre tel quel dans le constructeur
    add(connexionPanel);
    setSize(500, 500);

        connexionButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent actionEvent) {
            JOptionPane.showMessageDialog(connexionButton, "Erreur de connexion : mot de passe ou identiant incorrect");
        }
    });

    */
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
  //      $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
   /* private void $$$setupUI$$$() {
        connexionPanel = new JPanel();
        connexionPanel.setLayout(new BorderLayout(0, 0));
        headPanel = new JPanel();
        headPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        headPanel.setMaximumSize(new Dimension(400, 200));
        headPanel.setMinimumSize(new Dimension(400, 200));
        headPanel.setPreferredSize(new Dimension(400, 200));
        connexionPanel.add(headPanel, BorderLayout.NORTH);
        connexionLabel = new JLabel();
        connexionLabel.setAutoscrolls(false);
        connexionLabel.setFocusCycleRoot(false);
        connexionLabel.setForeground(new Color(-4188137));
        connexionLabel.setText("Connexion");
        connexionLabel.setVerticalTextPosition(0);
        headPanel.add(connexionLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        logoH2I = new JLabel();
        logoH2I.setAlignmentX(0.5f);
        logoH2I.setIcon(new ImageIcon(getClass().getResource("/ui/CopieLogo.png")));
        logoH2I.setText("");
        headPanel.add(logoH2I, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageCHUPP = new JLabel();
        imageCHUPP.setIcon(new ImageIcon(getClass().getResource("/ui/chupp.png")));
        imageCHUPP.setInheritsPopupMenu(true);
        imageCHUPP.setText("");
        headPanel.add(imageCHUPP, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        westPanel = new JPanel();
        westPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        connexionPanel.add(westPanel, BorderLayout.WEST);
        identifiantLabel = new JLabel();
        identifiantLabel.setText("Identifiant :");
        westPanel.add(identifiantLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mdpLabel = new JLabel();
        mdpLabel.setText("Mot de passe :");
        westPanel.add(mdpLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eastPanel = new JPanel();
        eastPanel.setLayout(new BorderLayout(0, 0));
        connexionPanel.add(eastPanel, BorderLayout.SOUTH);
        connexionButton = new JButton();
        connexionButton.setHorizontalAlignment(0);
        connexionButton.setHorizontalTextPosition(0);
        connexionButton.setText("Connexion");
        eastPanel.add(connexionButton, BorderLayout.EAST);
        resultPanel = new JPanel();
        resultPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        eastPanel.add(resultPanel, BorderLayout.CENTER);
        southPanel = new JPanel();
        southPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        connexionPanel.add(southPanel, BorderLayout.EAST);
        identifiantTextField = new JTextField();
        identifiantTextField.setColumns(0);
        southPanel.add(identifiantTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField = new JPasswordField();
        southPanel.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }
*/
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return connexionPanel;
    }

    /*
    public static void main(String[] args) {
        JFrame frame = new JFrame("essaisConnexion");
        frame.setContentPane(new essaisConnexion().connexionPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
*/
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    /*
    private void $$$setupUI$$$() {
        connexionPanel = new JPanel();
        connexionPanel.setLayout(new BorderLayout(0, 0));
        headPanel = new JPanel();
        headPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        headPanel.setMaximumSize(new Dimension(400, 200));
        headPanel.setMinimumSize(new Dimension(400, 200));
        headPanel.setPreferredSize(new Dimension(400, 200));
        connexionPanel.add(headPanel, BorderLayout.NORTH);
        connexionLabel = new JLabel();
        connexionLabel.setAutoscrolls(false);
        connexionLabel.setFocusCycleRoot(false);
        connexionLabel.setForeground(new Color(-4188137));
        connexionLabel.setText("Connexion");
        connexionLabel.setVerticalTextPosition(0);
        headPanel.add(connexionLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        logoH2I = new JLabel();
        logoH2I.setAlignmentX(0.5f);
        logoH2I.setIcon(new ImageIcon(getClass().getResource("/CopieLogo.png")));
        logoH2I.setText("");
        headPanel.add(logoH2I, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageCHUPP = new JLabel();
        imageCHUPP.setIcon(new ImageIcon(getClass().getResource("/chupp.png")));
        imageCHUPP.setInheritsPopupMenu(true);
        imageCHUPP.setText("");
        headPanel.add(imageCHUPP, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        westPanel = new JPanel();
        westPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        connexionPanel.add(westPanel, BorderLayout.WEST);
        identifiantLabel = new JLabel();
        identifiantLabel.setText("Identifiant :");
        westPanel.add(identifiantLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mdpLabel = new JLabel();
        mdpLabel.setText("Mot de passe :");
        westPanel.add(mdpLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eastPanel = new JPanel();
        eastPanel.setLayout(new BorderLayout(0, 0));
        connexionPanel.add(eastPanel, BorderLayout.SOUTH);
        connexionButton = new JButton();
        connexionButton.setHorizontalAlignment(0);
        connexionButton.setHorizontalTextPosition(0);
        connexionButton.setText("Connexion");
        eastPanel.add(connexionButton, BorderLayout.EAST);
        resultPanel = new JPanel();
        resultPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        eastPanel.add(resultPanel, BorderLayout.CENTER);
        southPanel = new JPanel();
        southPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        connexionPanel.add(southPanel, BorderLayout.EAST);
        identifiantTextField = new JTextField();
        identifiantTextField.setColumns(0);
        southPanel.add(identifiantTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField = new JPasswordField();
        southPanel.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }
*/
    /**
     * @noinspection ALL
     */
    /*
    public JComponent $$$getRootComponent$$$() {
        return connexionPanel;
    }
    */
}
