package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;


public class AcceuilMedecin extends JPanel {
    public JPanel panel1;
    private JPanel jPanelNorth;
    private JButton jButtonAccesPACS;
    private JButton jButtonRedactionCR;
    private JButton jButtonNumerisation;
    private JButton jButtonListePatient;
    private JLabel jLabelNomMed;
    private JLabel jLabelIconMed;
    private JLabel jLabelDateJr;

    public AcceuilMedecin() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setPreferredSize(new Dimension(500, 500));
        jPanelNorth = new JPanel();
        jPanelNorth.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(jPanelNorth, BorderLayout.NORTH);
        jLabelNomMed = new JLabel();
        jLabelNomMed.setText("Dr MARTIN Frédéric");
        jPanelNorth.add(jLabelNomMed, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jLabelIconMed = new JLabel();
        jLabelIconMed.setIcon(new ImageIcon(getClass().getResource("/icone medecin.png")));
        jLabelIconMed.setText("");
        jPanelNorth.add(jLabelIconMed, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jLabelDateJr = new JLabel();
        jLabelDateJr.setText("07/02/2019");
        jPanelNorth.add(jLabelDateJr, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, BorderLayout.CENTER);
        jButtonAccesPACS = new JButton();
        jButtonAccesPACS.setBackground(new Color(-10286840));
        jButtonAccesPACS.setFocusable(false);
        jButtonAccesPACS.setForeground(new Color(-2431508));
        jButtonAccesPACS.setInheritsPopupMenu(false);
        jButtonAccesPACS.setText("Accès PACS");
        panel2.add(jButtonAccesPACS, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jButtonRedactionCR = new JButton();
        jButtonRedactionCR.setBackground(new Color(-13475040));
        jButtonRedactionCR.setForeground(new Color(-2431508));
        jButtonRedactionCR.setText("Rédaction de compte-rendu");
        panel2.add(jButtonRedactionCR, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jButtonNumerisation = new JButton();
        jButtonNumerisation.setBackground(new Color(-13420957));
        jButtonNumerisation.setForeground(new Color(-2431508));
        jButtonNumerisation.setText("Numérisation");
        panel2.add(jButtonNumerisation, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jButtonListePatient = new JButton();
        jButtonListePatient.setBackground(new Color(-6008551));
        jButtonListePatient.setForeground(new Color(-2431508));
        jButtonListePatient.setText("Liste des patients");
        panel2.add(jButtonListePatient, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
