package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import nf.Connexion;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RedactionCR extends JPanel {
    //private JPanel panel1;
    private JTextArea textArea1;
    private JButton enregsitrerButton;
    private JButton imprimerButton;
    private JButton associationDMRButton;
    private JButton jButtonAcceuil;
    private JButton jButtonRedactionCR;
    private JButton jButtonListePatients;
    private JButton jButtonNumerisation;
    private JButton jButtonAccesPACS;
    private JLabel jLabelDateJr;
    private JLabel jLabelIconDoctor;
    private JLabel jLabelCRredaction;
    public JPanel mainPanelRedac;
    private MainWindow mainWindow;
    private Connexion connexion;


    public RedactionCR(MainWindow mainWindow) {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        this.mainWindow = mainWindow;
        connexion = new Connexion();
        jButtonAcceuil.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                retourAcceuil();
            }
        });
    }


    public void retourAcceuil() {
        try {
            this.mainWindow.setContentPane(new AcceuilMedecin(mainWindow).panel1);
            this.mainWindow.revalidate();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "retour indisponible pour le moment");
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanelRedac = new JPanel();
        mainPanelRedac.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanelRedac.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Dr MARTIN Frédéric");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jLabelIconDoctor = new JLabel();
        jLabelIconDoctor.setIcon(new ImageIcon(getClass().getResource("/iconeDocteur.png")));
        jLabelIconDoctor.setText("");
        panel1.add(jLabelIconDoctor, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jLabelDateJr = new JLabel();
        jLabelDateJr.setText("07/02/2019");
        panel1.add(jLabelDateJr, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanelRedac.add(panel2, BorderLayout.WEST);
        jButtonAcceuil = new JButton();
        jButtonAcceuil.setText("Acceuil");
        panel2.add(jButtonAcceuil, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jButtonRedactionCR = new JButton();
        jButtonRedactionCR.setText("Rédaction compte-rendu");
        panel2.add(jButtonRedactionCR, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jButtonListePatients = new JButton();
        jButtonListePatients.setText("Liste des patients");
        panel2.add(jButtonListePatients, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jButtonNumerisation = new JButton();
        jButtonNumerisation.setText("Numérisation");
        panel2.add(jButtonNumerisation, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jButtonAccesPACS = new JButton();
        jButtonAccesPACS.setText("Accès PACS");
        panel2.add(jButtonAccesPACS, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        mainPanelRedac.add(panel3, BorderLayout.EAST);
        jLabelCRredaction = new JLabel();
        jLabelCRredaction.setText("Rédaction compte-rendu");
        panel3.add(jLabelCRredaction, BorderLayout.NORTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel4, BorderLayout.SOUTH);
        enregsitrerButton = new JButton();
        enregsitrerButton.setText("Enregsitrer");
        panel4.add(enregsitrerButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imprimerButton = new JButton();
        imprimerButton.setText("Imprimer");
        panel4.add(imprimerButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        associationDMRButton = new JButton();
        associationDMRButton.setText("Association DMR");
        panel4.add(associationDMRButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textArea1 = new JTextArea();
        panel3.add(textArea1, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanelRedac.add(panel5, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanelRedac;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }


    public JPanel getMainPanelRedac() {
        return mainPanelRedac;
    }

    public void setMainPanelRedac(JPanel mainPanelRedac) {
        this.mainPanelRedac = mainPanelRedac;
    }

    public JTextArea getTextArea1() {
        return textArea1;
    }

    public void setTextArea1(JTextArea textArea1) {
        this.textArea1 = textArea1;
    }

    public JButton getEnregsitrerButton() {
        return enregsitrerButton;
    }

    public void setEnregsitrerButton(JButton enregsitrerButton) {
        this.enregsitrerButton = enregsitrerButton;
    }

    public JButton getImprimerButton() {
        return imprimerButton;
    }

    public void setImprimerButton(JButton imprimerButton) {
        this.imprimerButton = imprimerButton;
    }

    public JButton getAssociationDMRButton() {
        return associationDMRButton;
    }

    public void setAssociationDMRButton(JButton associationDMRButton) {
        this.associationDMRButton = associationDMRButton;
    }

    public JButton getjButtonAcceuil() {
        return jButtonAcceuil;
    }

    public void setjButtonAcceuil(JButton jButtonAcceuil) {
        this.jButtonAcceuil = jButtonAcceuil;
    }

    public JButton getjButtonRedactionCR() {
        return jButtonRedactionCR;
    }

    public void setjButtonRedactionCR(JButton jButtonRedactionCR) {
        this.jButtonRedactionCR = jButtonRedactionCR;
    }

    public JButton getjButtonListePatients() {
        return jButtonListePatients;
    }

    public void setjButtonListePatients(JButton jButtonListePatients) {
        this.jButtonListePatients = jButtonListePatients;
    }

    public JButton getjButtonNumerisation() {
        return jButtonNumerisation;
    }

    public void setjButtonNumerisation(JButton jButtonNumerisation) {
        this.jButtonNumerisation = jButtonNumerisation;
    }

    public JButton getjButtonAccesPACS() {
        return jButtonAccesPACS;
    }

    public void setjButtonAccesPACS(JButton jButtonAccesPACS) {
        this.jButtonAccesPACS = jButtonAccesPACS;
    }

    public JLabel getjLabelDateJr() {
        return jLabelDateJr;
    }

    public void setjLabelDateJr(JLabel jLabelDateJr) {
        this.jLabelDateJr = jLabelDateJr;
    }
}
